# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

default_game = ChessGame.create!(save_name: "default")

row1 = ChessBoardRow.create!(chess_game_id: default_game.id, row_index: 0)
row2 = ChessBoardRow.create!(chess_game_id: default_game.id, row_index: 1)
row3 = ChessBoardRow.create!(chess_game_id: default_game.id, row_index: 2)
row4 = ChessBoardRow.create!(chess_game_id: default_game.id, row_index: 3)
row5 = ChessBoardRow.create!(chess_game_id: default_game.id, row_index: 4)
row6 = ChessBoardRow.create!(chess_game_id: default_game.id, row_index: 5)
row7 = ChessBoardRow.create!(chess_game_id: default_game.id, row_index: 6)
row8 = ChessBoardRow.create!(chess_game_id: default_game.id, row_index: 7)

ChessBoardSquare.create!(chess_board_row_id: row1.id, square_index: 0, chess_piece_image: "<img class='black-rook black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c23687e54b-210x210.png'>")
ChessBoardSquare.create!(chess_board_row_id: row1.id, square_index: 1, chess_piece_image: "<img class='black-knight black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c23650ee18.png'>")
ChessBoardSquare.create!(chess_board_row_id: row1.id, square_index: 2, chess_piece_image: "<img class='black-bishop black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235734a67.png'>")
ChessBoardSquare.create!(chess_board_row_id: row1.id, square_index: 3, chess_piece_image: "<img class='black-queen black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235abcd0c.png'>")
ChessBoardSquare.create!(chess_board_row_id: row1.id, square_index: 4, chess_piece_image: "<img class='black-king black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c236018946.png'>")
ChessBoardSquare.create!(chess_board_row_id: row1.id, square_index: 5, chess_piece_image: "<img class='black-bishop black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235734a67.png'>")
ChessBoardSquare.create!(chess_board_row_id: row1.id, square_index: 6, chess_piece_image: "<img class='black-knight black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c23650ee18.png'>")
ChessBoardSquare.create!(chess_board_row_id: row1.id, square_index: 7, chess_piece_image: "<img class='black-rook black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c23687e54b-210x210.png'>")

ChessBoardSquare.create!(chess_board_row_id: row2.id, square_index: 0, chess_piece_image: "<img class='black-pawn black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235ca2856.png'>")
ChessBoardSquare.create!(chess_board_row_id: row2.id, square_index: 1, chess_piece_image: "<img class='black-pawn black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235ca2856.png'>")
ChessBoardSquare.create!(chess_board_row_id: row2.id, square_index: 2, chess_piece_image: "<img class='black-pawn black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235ca2856.png'>")
ChessBoardSquare.create!(chess_board_row_id: row2.id, square_index: 3, chess_piece_image: "<img class='black-pawn black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235ca2856.png'>")
ChessBoardSquare.create!(chess_board_row_id: row2.id, square_index: 4, chess_piece_image: "<img class='black-pawn black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235ca2856.png'>")
ChessBoardSquare.create!(chess_board_row_id: row2.id, square_index: 5, chess_piece_image: "<img class='black-pawn black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235ca2856.png'>")
ChessBoardSquare.create!(chess_board_row_id: row2.id, square_index: 6, chess_piece_image: "<img class='black-pawn black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235ca2856.png'>")
ChessBoardSquare.create!(chess_board_row_id: row2.id, square_index: 7, chess_piece_image: "<img class='black-pawn black-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235ca2856.png'>")

ChessBoardSquare.create!(chess_board_row_id: row3.id, square_index: 0)
ChessBoardSquare.create!(chess_board_row_id: row3.id, square_index: 1)
ChessBoardSquare.create!(chess_board_row_id: row3.id, square_index: 2)
ChessBoardSquare.create!(chess_board_row_id: row3.id, square_index: 3)
ChessBoardSquare.create!(chess_board_row_id: row3.id, square_index: 4)
ChessBoardSquare.create!(chess_board_row_id: row3.id, square_index: 5)
ChessBoardSquare.create!(chess_board_row_id: row3.id, square_index: 6)
ChessBoardSquare.create!(chess_board_row_id: row3.id, square_index: 7)

ChessBoardSquare.create!(chess_board_row_id: row4.id, square_index: 0)
ChessBoardSquare.create!(chess_board_row_id: row4.id, square_index: 1)
ChessBoardSquare.create!(chess_board_row_id: row4.id, square_index: 2)
ChessBoardSquare.create!(chess_board_row_id: row4.id, square_index: 3)
ChessBoardSquare.create!(chess_board_row_id: row4.id, square_index: 4)
ChessBoardSquare.create!(chess_board_row_id: row4.id, square_index: 5)
ChessBoardSquare.create!(chess_board_row_id: row4.id, square_index: 6)
ChessBoardSquare.create!(chess_board_row_id: row4.id, square_index: 7)

ChessBoardSquare.create!(chess_board_row_id: row5.id, square_index: 0)
ChessBoardSquare.create!(chess_board_row_id: row5.id, square_index: 1)
ChessBoardSquare.create!(chess_board_row_id: row5.id, square_index: 2)
ChessBoardSquare.create!(chess_board_row_id: row5.id, square_index: 3)
ChessBoardSquare.create!(chess_board_row_id: row5.id, square_index: 4)
ChessBoardSquare.create!(chess_board_row_id: row5.id, square_index: 5)
ChessBoardSquare.create!(chess_board_row_id: row5.id, square_index: 6)
ChessBoardSquare.create!(chess_board_row_id: row5.id, square_index: 7)

ChessBoardSquare.create!(chess_board_row_id: row6.id, square_index: 0)
ChessBoardSquare.create!(chess_board_row_id: row6.id, square_index: 1)
ChessBoardSquare.create!(chess_board_row_id: row6.id, square_index: 2)
ChessBoardSquare.create!(chess_board_row_id: row6.id, square_index: 3)
ChessBoardSquare.create!(chess_board_row_id: row6.id, square_index: 4)
ChessBoardSquare.create!(chess_board_row_id: row6.id, square_index: 5)
ChessBoardSquare.create!(chess_board_row_id: row6.id, square_index: 6)
ChessBoardSquare.create!(chess_board_row_id: row6.id, square_index: 7)

ChessBoardSquare.create!(chess_board_row_id: row7.id, square_index: 0, chess_piece_image: "<img class='white-pawn white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2361c0792.png'>")
ChessBoardSquare.create!(chess_board_row_id: row7.id, square_index: 1, chess_piece_image: "<img class='white-pawn white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2361c0792.png'>")
ChessBoardSquare.create!(chess_board_row_id: row7.id, square_index: 2, chess_piece_image: "<img class='white-pawn white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2361c0792.png'>")
ChessBoardSquare.create!(chess_board_row_id: row7.id, square_index: 3, chess_piece_image: "<img class='white-pawn white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2361c0792.png'>")
ChessBoardSquare.create!(chess_board_row_id: row7.id, square_index: 4, chess_piece_image: "<img class='white-pawn white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2361c0792.png'>")
ChessBoardSquare.create!(chess_board_row_id: row7.id, square_index: 5, chess_piece_image: "<img class='white-pawn white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2361c0792.png'>")
ChessBoardSquare.create!(chess_board_row_id: row7.id, square_index: 6, chess_piece_image: "<img class='white-pawn white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2361c0792.png'>")
ChessBoardSquare.create!(chess_board_row_id: row7.id, square_index: 7, chess_piece_image: "<img class='white-pawn white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2361c0792.png'>")

ChessBoardSquare.create!(chess_board_row_id: row8.id, square_index: 0, chess_piece_image: "<img class='white-rook white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2366cc7ae.png'>")
ChessBoardSquare.create!(chess_board_row_id: row8.id, square_index: 1, chess_piece_image: "<img class='white-knight white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c236365e2d.png'>")
ChessBoardSquare.create!(chess_board_row_id: row8.id, square_index: 2, chess_piece_image: "<img class='white-bishop white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c23557ae70.png'>")
ChessBoardSquare.create!(chess_board_row_id: row8.id, square_index: 3, chess_piece_image: "<img class='white-queen white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235e690a0.png'>")
ChessBoardSquare.create!(chess_board_row_id: row8.id, square_index: 4, chess_piece_image: "<img class='white-king white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c23592247c.png'>")
ChessBoardSquare.create!(chess_board_row_id: row8.id, square_index: 5, chess_piece_image: "<img class='white-bishop white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c23557ae70.png'>")
ChessBoardSquare.create!(chess_board_row_id: row8.id, square_index: 6, chess_piece_image: "<img class='white-knight white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c236365e2d.png'>")
ChessBoardSquare.create!(chess_board_row_id: row8.id, square_index: 7, chess_piece_image: "<img class='white-rook white-piece chess-piece' src='http://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c2366cc7ae.png'>")

